### ISSUE TITLE
create-flask-app

### ISSUE THREAD

**Issue by AndreMaciel66** [greendatalab/codash#1]

**Comment by Kushagratandon12** [comment]
Hi AndreMacie I can help you in building the Flask-App for this project 

1.  Create a flask app.py where you can send a post request from your react-js script something like this 
```
const res = await axios.post(
      "http://127.0.0.1:5000/flask",
      JSON.stringify(emails),
      {
        headers: {
          "Content-Type": "application/json",
        },
      }
    );
```

The above URL 'http://127.0.0.1:5000/flask' will be handled by flask.py file where I will be fetching the request send from react-js and doing some processing if required.

Please provide further details.
